resources:
  - auth/deployment.yaml
  - auth/service.yaml

  - expense/deployment.yaml
  - expense/service.yaml

  - ai/deployment.yaml
  - ai/service.yaml

  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-pvc.yaml

  - ingress/ingress.yaml