apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.ai.name }}
  labels:
    app: {{ .Values.ai.name }}
spec:

  selector:
    app: {{ .Values.ai.name }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ai.service.port }}
      targetPort: {{ .Values.ai.containerPort }}

  type: ClusterIP