apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Values.auth.name }}-monitor

  labels:
    release: monitoring

spec:

  selector:
    matchLabels:
      app: {{ .Values.auth.name }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s