apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.expense.name }}
  labels:
    app: {{ .Values.expense.name }}
spec:

  selector:
    app: {{ .Values.expense.name }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.expense.service.port }}
      targetPort: {{ .Values.expense.containerPort }}

  env:
    - name: DATABASE_URL
      value: "postgresql://postgres:postgres@postgres-service:5432/finops"

    - name: KAFKA_BOOTSTRAP_SERVERS
      value: "{{ .Values.kafka.bootstrapServers }}"

  type: ClusterIP